name: "Flutter Dependencies"
description: "Installs Flutter and any other dependencies required for the build"
runs:
  using: "composite"
  steps:
    - name: Get stable flutter
      id: setup_flutter
      uses: subosito/flutter-action@v2
      with:
        # NB! Keep up-to-date with the flutter version used for development
        flutter-version: "3.35.3"
        channel: "stable"

    - name: Prepare build directory
      id: prepare_build
      shell: bash
      run: |
        flutter clean
        rm -rf build/*
        rm -rf web/src/mm2/*
        rm -rf web/src/kdfi/*
        rm -rf web/dist/*
